version: "2"
services:
  whoami:
    image: bee42/whoami:2.2.0
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:examples.com"

  traefik:
    image: traefik:v1.7.20
    command: --api.dashboard=true --docker --docker.exposedbydefault=false --docker.domain=example.com --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
