apiVersion: v1
appVersion: "1.0.0"
version: "0.0.2"
description: A Helm chart for simple whoami hello
name: whoami
keywords:
- demo
- kubernetes
- helm
- whoami
home: https://bee42.com/
icon: https://bee42.com/images/logo.svg
sources:
- https://gitlab.bee42.com/containers/examples/whoami
maintainers:
- name: Peter Rossbach
  email: peter.rossbach@bee42.com
dependencies:
- name: ingress-nginx
  version: 3.23.0
  condition: nginx-ingress.enabled
  repository: https://kubernetes.github.io/ingress-nginx    
